spring:
  flyway:
    enabled: false
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:demo}
    username: ${DB_USER:demo}
    password: ${DB_PASSWORD:demo}
  jpa:
    hibernate:
      ddl-auto: update

#HASTA EL PUNTO 11 - 11 YA NO
#spring:
  #application:
    #name: "Mi App (DEV)"
#logging:
  #level:
    #root: DEBUG