spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:demo}
    username: ${DB_USER:demo}
    password: ${DB_PASSWORD:demo}
  application:
    name: "Mi App (PROD)"
  logging:
    level:
      root: WARN

#spring:
  #application:
    #name: "Mi App (PROD)"
#logging:
  #level:
    #root: WARN