spring:
  profiles:
    active: dev
  application:
    name: "Mi App"
  logging:
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
    level:
      root: INFO
      org.springframework.web: INFO
      es.fplumara.dam2.springdemo.services: DEBUG
api:
  url: "https://example.com"
  timeout-ms: 2000

#PARA EL PASO 8
#spring:
  #profiles:
    #active: prod
  #application:
    #name: "Mi App"
  #logging:
    #level:
      #root: INFO
#api:
  #url: ${API_URL:https://example.com}
  #timeout-ms: ${API_TIMEOUT_MS:2000}

#OPCIÃ“N B - PERFIL "POR DEFECTO"
#spring:
  #profiles:
    #active: dev

#url: "https://example.com"
    #timeout-ms: 2000