spring:
  application:
    name: "Mi App"
logging:
  level:
    root: INFO
api:
  url: "https://example.com"
  timeout-ms: 150

#OPCIÃ“N B - PERFIL "POR DEFECTO"
#spring:
  #profiles:
    #active: dev